'use strict';

const DOWNLOAD_STATUSES = Object.freeze({
    PENDING: 'pending',
    PREPARING: 'preparing',
    DOWNLOADING: 'downloading',
    PAUSING: 'pausing',
    PAUSED: 'paused',
    RESUMING: 'resuming',
    VERIFYING: 'verifying',
    INSTALLING: 'installing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
});

function nowIso(clock = Date) {
    return new clock().toISOString();
}

function normalizePlatform(platform) {
    return String(platform || '').trim().toLowerCase();
}

function normalizeTask(input = {}, deps = {}) {
    const ts = input.createdAt || nowIso(deps.clock);
    const status = input.status || DOWNLOAD_STATUSES.PENDING;
    return {
        id: String(input.id || ''),
        identityKey: String(input.identityKey || ''),
        gameId: input.gameId ? String(input.gameId) : null,
        canonicalGameId: input.canonicalGameId ? String(input.canonicalGameId) : null,
        title: String(input.title || 'Unknown Game'),
        coverUrl: input.coverUrl || null,
        heroUrl: input.heroUrl || null,

        platform: normalizePlatform(input.platform),
        accountId: input.accountId ? String(input.accountId) : null,
        accountDisplayName: input.accountDisplayName ? String(input.accountDisplayName) : null,
        providerProductId: input.providerProductId ? String(input.providerProductId) : null,
        providerAppName: input.providerAppName ? String(input.providerAppName) : null,
        gogProductId: input.gogProductId ? String(input.gogProductId) : null,
        contentSystemProductId: input.contentSystemProductId ? String(input.contentSystemProductId) : null,
        gogdlAppName: input.gogdlAppName ? String(input.gogdlAppName) : null,
        identitySource: input.identitySource ? String(input.identitySource) : null,
        ownershipVerified: input.ownershipVerified === true,
        secureLinkVerified: input.secureLinkVerified === true,
        verifiedBuildId: input.verifiedBuildId ? String(input.verifiedBuildId) : null,
        verifiedBuildGeneration: Number.isFinite(Number(input.verifiedBuildGeneration)) ? Number(input.verifiedBuildGeneration) : null,
        verifiedBuildCount: Number.isFinite(Number(input.verifiedBuildCount)) ? Number(input.verifiedBuildCount) : null,
        supportPath: input.supportPath ? String(input.supportPath) : null,
        language: input.language ? String(input.language) : null,

        installRoot: input.installRoot ? String(input.installRoot) : null,
        installFolder: input.installFolder ? String(input.installFolder) : null,
        installPath: input.installPath ? String(input.installPath) : null,
        installDriveRoot: input.installDriveRoot ? String(input.installDriveRoot) : null,
        installParentPath: input.installParentPath ? String(input.installParentPath) : null,
        installPathCreatedByBaddel: input.installPathCreatedByBaddel === true,
        installPathPreflightAt: input.installPathPreflightAt || null,
        installPathWritable: input.installPathWritable == null ? null : input.installPathWritable === true,
        freeSpaceBytesAtQueue: input.freeSpaceBytesAtQueue == null ? null : (Number.isFinite(Number(input.freeSpaceBytesAtQueue)) ? Number(input.freeSpaceBytesAtQueue) : null),
        requiredSpaceBytes: input.requiredSpaceBytes == null ? null : (Number.isFinite(Number(input.requiredSpaceBytes)) ? Number(input.requiredSpaceBytes) : null),
        diskSafetyMarginBytes: input.diskSafetyMarginBytes == null ? null : (Number.isFinite(Number(input.diskSafetyMarginBytes)) ? Number(input.diskSafetyMarginBytes) : null),
        partialDeletionEligible: input.partialDeletionEligible === true,
        partialDeletionMarkerPath: input.partialDeletionMarkerPath ? String(input.partialDeletionMarkerPath) : null,
        ownershipNonce: input.ownershipNonce ? String(input.ownershipNonce) : null,
        installPathOwnershipPreparedAt: input.installPathOwnershipPreparedAt || null,
        partialDeletedAt: input.partialDeletedAt || null,

        status,
        statusMessage: input.statusMessage ? String(input.statusMessage) : '',
        stage: input.stage ? String(input.stage) : status,

        progressPercent: input.progressPercent == null ? null : (Number.isFinite(Number(input.progressPercent)) ? Number(input.progressPercent) : null),
        downloadedBytes: Number.isFinite(Number(input.downloadedBytes)) ? Number(input.downloadedBytes) : 0,
        totalBytes: input.totalBytes == null ? null : (Number.isFinite(Number(input.totalBytes)) ? Number(input.totalBytes) : null),
        transferDownloadedBytes: input.transferDownloadedBytes == null ? null : (Number.isFinite(Number(input.transferDownloadedBytes)) ? Number(input.transferDownloadedBytes) : null),
        transferTotalBytes: input.transferTotalBytes == null ? null : (Number.isFinite(Number(input.transferTotalBytes)) ? Number(input.transferTotalBytes) : null),
        installedDiskSizeBytes: input.installedDiskSizeBytes == null ? null : (Number.isFinite(Number(input.installedDiskSizeBytes)) ? Number(input.installedDiskSizeBytes) : null),
        verifiedBytes: input.verifiedBytes == null ? null : (Number.isFinite(Number(input.verifiedBytes)) ? Number(input.verifiedBytes) : null),
        providerProgressMode: input.providerProgressMode ? String(input.providerProgressMode) : null,
        providerReportedPercent: input.providerReportedPercent == null ? null : (Number.isFinite(Number(input.providerReportedPercent)) ? Number(input.providerReportedPercent) : null),
        providerDownloadedBytes: input.providerDownloadedBytes == null ? null : (Number.isFinite(Number(input.providerDownloadedBytes)) ? Number(input.providerDownloadedBytes) : null),
        providerTotalBytes: input.providerTotalBytes == null ? null : (Number.isFinite(Number(input.providerTotalBytes)) ? Number(input.providerTotalBytes) : null),
        stableTotalBytes: input.stableTotalBytes == null ? null : (Number.isFinite(Number(input.stableTotalBytes)) ? Number(input.stableTotalBytes) : null),
        resumeBaseDownloadedBytes: input.resumeBaseDownloadedBytes == null ? null : (Number.isFinite(Number(input.resumeBaseDownloadedBytes)) ? Number(input.resumeBaseDownloadedBytes) : null),
        sessionDownloadedBytes: input.sessionDownloadedBytes == null ? null : (Number.isFinite(Number(input.sessionDownloadedBytes)) ? Number(input.sessionDownloadedBytes) : null),
        sessionTotalBytes: input.sessionTotalBytes == null ? null : (Number.isFinite(Number(input.sessionTotalBytes)) ? Number(input.sessionTotalBytes) : null),
        progressMode: input.progressMode ? String(input.progressMode) : null,
        progressSource: input.progressSource ? String(input.progressSource) : null,
        totalBytesSource: input.totalBytesSource ? String(input.totalBytesSource) : null,
        downloadedBytesSource: input.downloadedBytesSource ? String(input.downloadedBytesSource) : null,
        checkpointDownloadedBytes: input.checkpointDownloadedBytes == null ? null : (Number.isFinite(Number(input.checkpointDownloadedBytes)) ? Number(input.checkpointDownloadedBytes) : null),
        checkpointTotalBytes: input.checkpointTotalBytes == null ? null : (Number.isFinite(Number(input.checkpointTotalBytes)) ? Number(input.checkpointTotalBytes) : null),
        checkpointProgressPercent: input.checkpointProgressPercent == null ? null : (Number.isFinite(Number(input.checkpointProgressPercent)) ? Number(input.checkpointProgressPercent) : null),
        checkpointProgressSource: input.checkpointProgressSource ? String(input.checkpointProgressSource) : null,
        checkpointSessionId: input.checkpointSessionId ? String(input.checkpointSessionId) : null,
        checkpointAt: input.checkpointAt || null,
        downloadSpeedBps: Number.isFinite(Number(input.downloadSpeedBps)) ? Number(input.downloadSpeedBps) : 0,
        downloadSpeedRawBps: input.downloadSpeedRawBps == null ? null : (Number.isFinite(Number(input.downloadSpeedRawBps)) ? Number(input.downloadSpeedRawBps) : null),
        downloadSpeedSmoothedBps: input.downloadSpeedSmoothedBps == null ? null : (Number.isFinite(Number(input.downloadSpeedSmoothedBps)) ? Number(input.downloadSpeedSmoothedBps) : null),
        diskUsageBps: Number.isFinite(Number(input.diskUsageBps)) ? Number(input.diskUsageBps) : 0,
        etaSeconds: input.etaSeconds == null ? null : (Number.isFinite(Number(input.etaSeconds)) ? Number(input.etaSeconds) : null),
        bytesWritten: input.bytesWritten == null ? null : (Number.isFinite(Number(input.bytesWritten)) ? Number(input.bytesWritten) : null),
        writtenBytes: input.writtenBytes == null ? null : (Number.isFinite(Number(input.writtenBytes)) ? Number(input.writtenBytes) : null),
        rawDownloadedBytes: input.rawDownloadedBytes == null ? null : (Number.isFinite(Number(input.rawDownloadedBytes)) ? Number(input.rawDownloadedBytes) : null),
        rawDownloadSpeedBps: input.rawDownloadSpeedBps == null ? null : (Number.isFinite(Number(input.rawDownloadSpeedBps)) ? Number(input.rawDownloadSpeedBps) : null),
        decompressionSpeedBps: input.decompressionSpeedBps == null ? null : (Number.isFinite(Number(input.decompressionSpeedBps)) ? Number(input.decompressionSpeedBps) : null),
        diskWriteSpeedBps: input.diskWriteSpeedBps == null ? null : (Number.isFinite(Number(input.diskWriteSpeedBps)) ? Number(input.diskWriteSpeedBps) : null),
        diskReadSpeedBps: input.diskReadSpeedBps == null ? null : (Number.isFinite(Number(input.diskReadSpeedBps)) ? Number(input.diskReadSpeedBps) : null),
        telemetryState: input.telemetryState ? String(input.telemetryState) : 'measuring',
        networkState: input.networkState ? String(input.networkState) : 'measuring',
        stallReason: input.stallReason ? String(input.stallReason) : null,
        retryable: input.retryable == null ? null : input.retryable === true,
        retryAfter: input.retryAfter == null ? null : (Number.isFinite(Number(input.retryAfter)) ? Number(input.retryAfter) : null),
        failureDetails: input.failureDetails && typeof input.failureDetails === 'object' ? input.failureDetails : null,
        failureCategory: input.failureCategory ? String(input.failureCategory) : null,
        failureSuggestedAction: input.failureSuggestedAction ? String(input.failureSuggestedAction) : null,
        errorTechnicalSummary: input.errorTechnicalSummary ? String(input.errorTechnicalSummary) : null,
        autoResumeEligible: input.autoResumeEligible == null ? null : input.autoResumeEligible === true,
        expectedTotalBytes: input.expectedTotalBytes == null ? null : (Number.isFinite(Number(input.expectedTotalBytes)) ? Number(input.expectedTotalBytes) : null),
        expectedDownloadBytes: input.expectedDownloadBytes == null ? null : (Number.isFinite(Number(input.expectedDownloadBytes)) ? Number(input.expectedDownloadBytes) : null),
        expectedInstalledBytes: input.expectedInstalledBytes == null ? null : (Number.isFinite(Number(input.expectedInstalledBytes)) ? Number(input.expectedInstalledBytes) : null),
        sizeResolutionStatus: input.sizeResolutionStatus ? String(input.sizeResolutionStatus) : null,
        sizeResolutionFailureReason: input.sizeResolutionFailureReason ? String(input.sizeResolutionFailureReason) : null,
        unexpectedTotalBytes: input.unexpectedTotalBytes == null ? null : (Number.isFinite(Number(input.unexpectedTotalBytes)) ? Number(input.unexpectedTotalBytes) : null),
        progressRevision: Number.isInteger(Number(input.progressRevision)) ? Number(input.progressRevision) : 0,
        progressSessionId: input.progressSessionId ? String(input.progressSessionId) : null,
        taskRevision: Number.isInteger(Number(input.taskRevision)) ? Number(input.taskRevision) : 0,

        runtimeVersion: input.runtimeVersion ? String(input.runtimeVersion) : null,
        processPid: input.processPid == null ? null : (Number.isInteger(Number(input.processPid)) ? Number(input.processPid) : null),
        processStartedAt: input.processStartedAt || null,
        processExitedAt: input.processExitedAt || null,
        firstProviderOutputAt: input.firstProviderOutputAt || null,
        firstAuthoritativeProgressAt: input.firstAuthoritativeProgressAt || null,
        lastAuthoritativeProgressAt: input.lastAuthoritativeProgressAt || null,
        lastTransferCounterAt: input.lastTransferCounterAt || null,
        lastProviderActivityAt: input.lastProviderActivityAt || null,
        lastProviderSampleAt: input.lastProviderSampleAt || null,
        lastMeaningfulProgressAt: input.lastMeaningfulProgressAt || null,
        providerDiagnosticPath: input.providerDiagnosticPath ? String(input.providerDiagnosticPath) : null,
        pauseRequestedAt: input.pauseRequestedAt || null,
        resumeStartedAt: input.resumeStartedAt || null,
        resumeAttempts: Number.isInteger(Number(input.resumeAttempts)) ? Number(input.resumeAttempts) : 0,
        providerResumeSupported: input.providerResumeSupported == null ? null : input.providerResumeSupported === true,
        completionConfirmed: input.completionConfirmed === true,
        installedGameId: input.installedGameId ? String(input.installedGameId) : null,
        resolvedExecutablePath: input.resolvedExecutablePath ? String(input.resolvedExecutablePath) : null,
        libraryRegisteredAt: input.libraryRegisteredAt || null,
        providerCompletionReceipt: input.providerCompletionReceipt && typeof input.providerCompletionReceipt === 'object' ? input.providerCompletionReceipt : null,
        verificationStatus: input.verificationStatus ? String(input.verificationStatus) : null,
        verificationMethod: input.verificationMethod ? String(input.verificationMethod) : null,
        verificationExpectedFileCount: input.verificationExpectedFileCount == null ? null : (Number.isFinite(Number(input.verificationExpectedFileCount)) ? Number(input.verificationExpectedFileCount) : null),
        verificationVerifiedFileCount: input.verificationVerifiedFileCount == null ? null : (Number.isFinite(Number(input.verificationVerifiedFileCount)) ? Number(input.verificationVerifiedFileCount) : null),
        verificationExpectedBytes: input.verificationExpectedBytes == null ? null : (Number.isFinite(Number(input.verificationExpectedBytes)) ? Number(input.verificationExpectedBytes) : null),
        verificationActualBytes: input.verificationActualBytes == null ? null : (Number.isFinite(Number(input.verificationActualBytes)) ? Number(input.verificationActualBytes) : null),
        verificationExecutableFound: input.verificationExecutableFound == null ? null : input.verificationExecutableFound === true,
        verificationExecutablePath: input.verificationExecutablePath ? String(input.verificationExecutablePath) : null,
        verificationManifestFound: input.verificationManifestFound == null ? null : input.verificationManifestFound === true,
        recoveryReason: input.recoveryReason ? String(input.recoveryReason) : null,
        errorCode: input.errorCode ? String(input.errorCode) : null,
        errorMessage: input.errorMessage ? String(input.errorMessage) : null,
        retryCount: Number.isInteger(Number(input.retryCount)) ? Number(input.retryCount) : 0,

        createdAt: ts,
        queuedAt: input.queuedAt || ts,
        startedAt: input.startedAt || null,
        updatedAt: input.updatedAt || ts,
        completedAt: input.completedAt || null,
    };
}

module.exports = {
    DOWNLOAD_STATUSES,
    normalizeTask,
    normalizePlatform,
};


